# Generated by Django 6.0.2 on 2026-02-10 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата достижения')),
                ('image', models.ImageField(blank=True, upload_to='achievements/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('vk_link', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День')),
                ('time', models.TimeField(verbose_name='Время')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('age_group', models.CharField(max_length=100, verbose_name='Возрастная группа')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название праздника')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='holidays/', verbose_name='Фото')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('min_age', models.IntegerField(default=3, verbose_name='Минимальный возраст')),
                ('max_age', models.IntegerField(default=12, verbose_name='Максимальный возраст')),
                ('max_children', models.IntegerField(default=10, verbose_name='Максимум детей')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='partizan.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
        migrations.CreateModel(
            name='HolidayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('max_bookings', models.IntegerField(default=3, verbose_name='Максимум заявок')),
                ('current_bookings', models.IntegerField(default=0, verbose_name='Текущие заявки')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='partizan.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Дата праздника',
                'verbose_name_plural': 'Даты праздников',
                'unique_together': {('holiday', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FullOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('children_count', models.IntegerField(verbose_name='Количество детей')),
                ('age_of_children', models.CharField(max_length=200, verbose_name='Возраст детей')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partizan.holiday', verbose_name='Праздник')),
                ('holiday_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partizan.holidaydate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='QuickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partizan.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Быстрая заявка',
                'verbose_name_plural': 'Быстрые заявки',
            },
        ),
    ]
