# Generated by Django 6.0.2 on 2026-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AddField(
            model_name='achievement',
            name='age_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город проведения'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='competition_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название соревнования'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='place',
            field=models.IntegerField(choices=[(1, '1 место 🥇'), (2, '2 место 🥈'), (3, '3 место 🥉'), (4, 'Участие'), (5, 'Победа в номинации')], default=1, verbose_name='Место/награда'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название достижения'),
        ),
    ]
