# Generated by Django 6.0 on 2026-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0002_delete_about_delete_training_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Имя родителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('child_name', models.CharField(max_length=200, verbose_name='Имя ребенка')),
                ('child_age', models.IntegerField(verbose_name='Возраст ребенка')),
                ('age_group', models.CharField(choices=[('under_13', 'Дети до 13 лет'), ('13_16', 'Подростки 13-16 лет'), ('adult', 'Взрослые 17+')], max_length=20, verbose_name='Группа')),
                ('visit_type', models.CharField(choices=[('trial', 'Пробное занятие'), ('single', 'Разовое посещение'), ('subscription', 'Абонемент')], default='trial', max_length=20, verbose_name='Тип посещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на тренировку',
                'verbose_name_plural': 'Заявки на тренировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='age_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='competition_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название соревнования'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена (₽)'),
        ),
    ]
