# Generated by Django 6.0 on 2026-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0003_trainingregistration_alter_achievement_age_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingregistration',
            name='visit_type',
            field=models.CharField(choices=[('trial', 'Пробное занятие (бесплатно)'), ('single', 'Разовое посещение (700 ₽)'), ('subscription', 'Абонемент 8 занятий (4 000 ₽)')], default='trial', max_length=20, verbose_name='Тип посещения'),
        ),
    ]
