# Generated by Django 6.0 on 2026-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0004_alter_trainingregistration_visit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaydate',
            options={'ordering': ['date', 'time_slot'], 'verbose_name': 'Дата и время праздника', 'verbose_name_plural': 'Даты и время праздников'},
        ),
        migrations.AlterUniqueTogether(
            name='holidaydate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='time_slot',
            field=models.CharField(choices=[('10:00-12:00', '10:00 - 12:00'), ('12:00-14:00', '12:00 - 14:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00'), ('18:00-20:00', '18:00 - 20:00'), ('10:00-14:00', '10:00 - 14:00'), ('14:00-18:00', '14:00 - 18:00'), ('18:00-22:00', '18:00 - 22:00')], default='10:00-12:00', max_length=20, verbose_name='Временной слот'),
        ),
        migrations.AlterField(
            model_name='holidaydate',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaydate',
            unique_together={('holiday', 'date', 'time_slot')},
        ),
    ]
