# Generated by Django 6.0 on 2026-02-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0005_alter_holidaydate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaydate',
            name='max_bookings',
            field=models.IntegerField(default=2, verbose_name='Максимум заявок'),
        ),
    ]
