# Generated by Django 6.0.2 on 2026-02-26 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0006_alter_holidaydate_max_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='fullorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Полная заявка', 'verbose_name_plural': 'Полные заявки'},
        ),
        migrations.AlterModelOptions(
            name='holidaydate',
            options={'ordering': ['date', 'time_slot'], 'verbose_name': 'Занятый слот', 'verbose_name_plural': 'Занятые слоты'},
        ),
        migrations.AlterUniqueTogether(
            name='holidaydate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='holiday_date',
        ),
        migrations.AddField(
            model_name='fullorder',
            name='selected_date',
            field=models.DateField(null=True, verbose_name='Выбранная дата'),
        ),
        migrations.AddField(
            model_name='fullorder',
            name='selected_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Выбранное время'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='age_of_children',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Возраст детей'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='bookings_count',
            field=models.IntegerField(default=1, verbose_name='Количество заявок (макс 2)'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='children_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания слота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='hall_number',
            field=models.IntegerField(default=1, verbose_name='Номер зала'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название праздника'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='holidaydate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='holidaydate',
            name='time_slot',
            field=models.CharField(max_length=20, verbose_name='Временной слот'),
        ),
        migrations.RemoveField(
            model_name='holidaydate',
            name='available',
        ),
        migrations.RemoveField(
            model_name='holidaydate',
            name='current_bookings',
        ),
        migrations.RemoveField(
            model_name='holidaydate',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='holidaydate',
            name='max_bookings',
        ),
    ]
