# Generated by Django 6.0.2 on 2026-02-26 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0007_delete_contact_alter_fullorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на праздник', 'verbose_name_plural': 'Заявки на праздники'},
        ),
        migrations.AddField(
            model_name='fullorder',
            name='hall_number',
            field=models.IntegerField(default=1, verbose_name='Номер зала'),
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='selected_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Выбранная дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='selected_time',
            field=models.CharField(max_length=20, verbose_name='Выбранное время'),
        ),
    ]
