# Generated by Django 6.0.2 on 2026-02-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0008_alter_fullorder_options_fullorder_hall_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayDate',
        ),
    ]
