# Generated by Django 6.0 on 2026-03-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
