# Generated by Django 6.0 on 2026-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullorder',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение пользователя'),
        ),
    ]
