# Generated by Django 6.0 on 2026-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partizan', '0012_fullorder_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Полная заявка', 'verbose_name_plural': 'Полные заявки'},
        ),
        migrations.AddField(
            model_name='fullorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='selected_date',
            field=models.DateField(null=True, verbose_name='Выбранная дата'),
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='selected_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Выбранное время'),
        ),
    ]
